// SPDX-License-Identifier: GPL-3.0-only
package com.shilapi.xcertplay

import android.content.Context
import com.shilapi.xcertplay.host.R

/** Resolves UI copy to the fixed Simplified Chinese resource set. */
internal fun Context.uiText(source: String): String {
    val resource = UI_TEXT[source] ?: return source
    return getString(resource)
}

private val UI_TEXT = mapOf(
    "Car home" to R.string.ui_car_home,
    "Back" to R.string.ui_back,
    "YOUR PHONE. YOUR DRIVE." to R.string.ui_home_tag,
    "A familiar drive." to R.string.ui_familiar_drive,
    "Your maps, music and conversations.\nCarPlay, right here on your car display." to R.string.ui_maps_music,
    "WIRELESS CARPLAY" to R.string.ui_wireless_carplay,
    "Ready when you are" to R.string.ui_ready,
    "Connect phone" to R.string.ui_connect_phone,
    "Pair your iPhone with the car’s Bluetooth, then connect.\nKeep Bluetooth and Wi-Fi on." to R.string.ui_pair_bluetooth,
    "Open car hotspot settings" to R.string.ui_open_hotspot_settings,
    "Choose iPhone" to R.string.ui_choose_iphone,
    "Disconnect" to R.string.ui_disconnect,
    "Connect with USB" to R.string.ui_connect_usb,
    "Plug your iPhone into a USB data port.\nAllow CarPlay when your iPhone asks." to R.string.ui_usb_instructions,
    "Settings" to R.string.ui_settings,
    "Make DiPlay feel right for your car." to R.string.ui_make_diplay_yours,
    "Your drive, your way." to R.string.ui_your_drive,
    "Apply reconnects CarPlay for size, resolution, music buffer and frame rate. Other changes apply to your next connection." to R.string.ui_apply_reconnects,
    "Automatic connection" to R.string.ui_automatic_connection,
    "Connect when DiPlay opens" to R.string.ui_connect_on_open,
    "Use your last connection type and selected iPhone." to R.string.ui_last_connection_iphone,
    "Open after the car starts" to R.string.ui_open_after_start,
    "Availability depends on your head unit’s startup settings." to R.string.ui_startup_settings,
    "Wireless connection" to R.string.ui_wireless_connection,
    "Display and performance" to R.string.ui_display_performance,
    "Resolution" to R.string.ui_resolution,
    "Native" to R.string.ui_native,
    "80% · lighter load" to R.string.ui_80_light,
    "60% · lightest load" to R.string.ui_60_lightest,
    "Music buffer" to R.string.ui_music_buffer,
    "300 ms · default" to R.string.ui_300_default,
    "500 ms" to R.string.ui_500_ms,
    "1000 ms · most stable" to R.string.ui_1000_stable,
    "Frame rate" to R.string.ui_frame_rate,
    "30 fps · lighter load" to R.string.ui_30_fps_light,
    "60 fps · smoother motion" to R.string.ui_60_fps_smooth,
    "Efficient video" to R.string.ui_efficient_video,
    "Use HEVC. Leave off for the widest head-unit compatibility." to R.string.ui_hevc_compatibility,
    "Right-hand drive" to R.string.ui_right_hand_drive,
    "Place CarPlay’s controls closer to the driver." to R.string.ui_controls_driver,
    "Full screen" to R.string.ui_full_screen,
    "Hide the car’s system bars while CarPlay is open." to R.string.ui_hide_system_bars,
    "BYD navigation" to R.string.ui_byd_navigation,
    "Show phone navigation arrows, distance and street names on supported BYD displays. Vehicle compatibility varies." to R.string.ui_hud_cluster,
    "Navigation on HUD and instrument cluster" to R.string.ui_navigation_on_hud,
    "Permissions and connection help" to R.string.ui_permissions_help,
    "Nearby devices connects your iPhone. Microphone enables Siri and calls. Older Android versions also require Location for wireless setup. USB mode may ask for a local VPN connection." to R.string.ui_permission_explanation,
    "App permissions" to R.string.ui_app_permissions,
    "Bluetooth settings" to R.string.ui_bluetooth_settings,
    "Wireless connection help" to R.string.ui_wireless_help,
    "About and diagnostics" to R.string.ui_about_diagnostics,
    "About DiPlay" to R.string.ui_about_diplay,
    "Saving report…" to R.string.ui_saving_report,
    "Save diagnostic report" to R.string.ui_save_report,
    "Nothing is sent automatically. Protocol payloads and credentials are excluded." to R.string.ui_no_auto_send,
    "CarPlay, at home in your car." to R.string.ui_carplay_at_home,
    "An independent CarPlay receiver for Android head units. Wired and wireless connections run on the head unit, with local authentication. A standard iPhone can connect without a jailbreak, Mac, dongle or sign-in.\n\nThis preview uses an experimental accessory identity. Compatibility with every iPhone and head unit is still being tested. It is not an Apple-certified product." to R.string.ui_about_description,
    "Made possible by open source" to R.string.ui_open_source,
    "Receiver based on xcertplay, licensed under GPL-3.0. DiPlay’s interface follows DiAuto’s design, licensed under AGPL-3.0.\n\nIncludes AndroidX, Bouncy Castle, JmDNS and SLF4J. Source and license notices accompany this release.\n\nCarPlay and the CarPlay icon belong to Apple Inc. DiPlay is an independent project." to R.string.ui_license_credits,
    "Car hotspot is off" to R.string.ui_hotspot_off_title,
    "Open car settings" to R.string.ui_open_car_settings,
    "Connect" to R.string.ui_connect,
    "Cancel" to R.string.ui_cancel,
    "Wireless link" to R.string.ui_wireless_link_title,
    "Wi-Fi Direct · default" to R.string.ui_wifi_direct_default,
    "Car hotspot" to R.string.ui_car_hotspot,
    "DiPlay creates its own Wi-Fi Direct network for the iPhone." to R.string.ui_diplay_wifi_direct,
    "Hotspot name" to R.string.ui_hotspot_name,
    "Hotspot password" to R.string.ui_hotspot_password,
    "none" to R.string.ui_none,
    "Turn on the hotspot in the car settings first and enter the same name and password here. The iPhone joins this network for CarPlay. Changes apply to your next connection." to R.string.ui_hotspot_instructions,
    "Save" to R.string.ui_save,
    "Apply and reconnect" to R.string.ui_apply_reconnect,
    "CarPlay size" to R.string.ui_carplay_size,
    "Changes the size of CarPlay icons and text. Applying a size reconnects CarPlay." to R.string.ui_size_reconnect,
    "Turn on Bluetooth" to R.string.ui_turn_on_bluetooth,
    "Enable the car’s Bluetooth and pair your iPhone first." to R.string.ui_enable_pair_bluetooth,
    "Open Bluetooth" to R.string.ui_open_bluetooth,
    "Later" to R.string.ui_later,
    "Pair your iPhone" to R.string.ui_pair_iphone,
    "On your iPhone, open Settings → Bluetooth and pair with the car. Then return to DiPlay and choose Connect phone." to R.string.ui_pair_instructions,
    "Got it" to R.string.ui_got_it,
    "Choose your iPhone" to R.string.ui_choose_iphone_title,
    "Paired device" to R.string.ui_paired_device,
    "Pair another" to R.string.ui_pair_another,
    "Wireless connection help" to R.string.ui_wireless_connection_help_title,
    "Pair your iPhone with the car’s Bluetooth, keep Wi-Fi on, and allow CarPlay on the iPhone. Close any other phone-projection app.\n\nIf a previous projection app left its connection running, reset CarPlay Wi-Fi below and connect again. Your car’s normal internet Wi-Fi stays on." to R.string.ui_wireless_help_message,
    "Reset CarPlay Wi-Fi" to R.string.ui_reset_carplay_wifi,
    "Reset CarPlay Wi-Fi?" to R.string.ui_reset_carplay_wifi_title,
    "This ends the existing Wi-Fi Direct connection, including one left behind after reinstalling. Close other projection apps first. Your car’s internet Wi-Fi stays on." to R.string.ui_reset_wifi_message,
    "Reset and connect" to R.string.ui_reset_connect,
    "This head unit does not support Wi-Fi Direct." to R.string.ui_wifi_direct_unsupported,
    "Wi-Fi Direct is still busy. Close the other projection app and try again." to R.string.ui_wifi_direct_busy,
    "Could not reset Wi-Fi Direct. Close the other projection app and try again." to R.string.ui_wifi_direct_reset_failed,
    "Wireless permissions" to R.string.ui_wireless_permissions,
    "Allow Nearby devices and, on older Android versions, Location before resetting CarPlay Wi-Fi." to R.string.ui_wireless_permission_help,
    "Setup needs attention" to R.string.ui_setup_attention,
    "CarPlay connected" to R.string.ui_carplay_connected,
    "Connecting to your iPhone…" to R.string.ui_connecting_iphone,
    "Open CarPlay" to R.string.ui_open_carplay,
    "This head unit could not open a save location. Please try saving to Downloads again." to R.string.ui_save_location_unavailable,
    "This head unit has no available file picker to save the report." to R.string.ui_file_picker_unavailable,
    "Diagnostic report saved" to R.string.ui_report_saved,
    "Your report was saved to the selected location." to R.string.ui_report_saved_location,
    "Done" to R.string.ui_done,
    "Could not save the report" to R.string.ui_report_save_failed,
    "Check that storage is available, or choose another save location." to R.string.ui_report_save_help,
    "Choose location" to R.string.ui_choose_location,
    "Close" to R.string.ui_close,
    "App settings" to R.string.ui_app_settings,
    "Open this setting from your car’s Settings app." to R.string.ui_open_car_settings_from_system,
    "CarPlay connection running" to R.string.ui_connection_running,
    "CarPlay settings" to R.string.ui_carplay_settings,
    "Connection" to R.string.ui_connection,
    "Wireless CarPlay" to R.string.ui_wireless_carplay_setting,
    "Hotspot status" to R.string.ui_hotspot_status,
    "Location" to R.string.ui_location,
    "Startup" to R.string.ui_startup,
    "Auto-start on boot" to R.string.ui_auto_start_boot,
    "Start CarPlay automatically after device boot" to R.string.ui_auto_start_desc,
    "Audio" to R.string.ui_audio,
    "Advanced audio channel mapping" to R.string.ui_advanced_audio_mapping,
    "Route AAOS audio buses by CarPlay audio type" to R.string.ui_advanced_audio_desc,
    "Identity & appearance" to R.string.ui_identity_appearance,
    "Display & video" to R.string.ui_display_video,
    "Physical size basis" to R.string.ui_size_basis,
    "Widest width" to R.string.ui_widest_width,
    "Longest height" to R.string.ui_longest_height,
    "Physical length" to R.string.ui_physical_length,
    "HEVC H.265 video transport" to R.string.ui_hevc_transport,
    "HEVC software decoder" to R.string.ui_hevc_software_decoder,
    "Use software HEVC decoder" to R.string.ui_use_software_hevc,
    "Window" to R.string.ui_window,
    "Diagnostics" to R.string.ui_diagnostics,
    "Android 9 compatibility" to R.string.ui_android_9_compatibility,
    "Save and reconnect" to R.string.ui_save_reconnect,
    "EXIT APPLICATION" to R.string.ui_exit_application,
    "Discard changes and exit settings" to R.string.ui_discard_exit_settings,
    "MFI certificate & signing target" to R.string.ui_mfi_target,
    "Linux device path, for example /dev/i2c-1." to R.string.ui_linux_device_path,
    "Server address" to R.string.ui_server_address,
    "Token (optional)" to R.string.ui_token_optional,
    "Address must start with http:// or https://. Token is optional and sent as an Authorization bearer token." to R.string.ui_address_token_help,
    "Manufacturer" to R.string.ui_manufacturer,
    "Model" to R.string.ui_model,
    "OEM label" to R.string.ui_oem_label,
    "Report location to iPhone" to R.string.ui_report_location,
    "Report Android location to the iPhone" to R.string.ui_report_android_location,
    "Sends precise Android location as CarPlay GPS data when the iPhone requests it." to R.string.ui_location_explanation,
    "Debug logs" to R.string.ui_debug_logs,
    "Show on-screen debug logs" to R.string.ui_show_debug_logs,
    "AirPlay icon" to R.string.ui_airplay_icon,
    "Choose image" to R.string.ui_choose_image,
    "Default icon" to R.string.ui_default_icon,
    "Custom 1:1 icon" to R.string.ui_custom_icon,
    "Default placeholder icon" to R.string.ui_default_placeholder_icon,
    "Driving side" to R.string.ui_driving_side,
    "Left-hand drive" to R.string.ui_left_hand_drive,
    "Right-hand drive" to R.string.ui_right_hand_drive_label,
    "Fullscreen" to R.string.ui_fullscreen,
    "Hide top bar" to R.string.ui_hide_top_bar,
    "Hide the status bar" to R.string.ui_hide_status_bar,
    "Hide bottom bar" to R.string.ui_hide_bottom_bar,
    "Hide the navigation bar" to R.string.ui_hide_navigation_bar,
    "Safe area" to R.string.ui_safe_area,
    "Set" to R.string.ui_safe_area_set,
    "Reset" to R.string.ui_reset,
    "Draw outside safe area" to R.string.ui_draw_outside_safe_area,
    "Allow CarPlay UI outside the safe area" to R.string.ui_allow_outside_safe_area,
    "Wi-Fi session" to R.string.ui_wifi_session,
    "Manual hotspot" to R.string.ui_manual_hotspot,
    "Band" to R.string.ui_band,
    "Auto" to R.string.ui_auto,
    "Channel (0 = auto)" to R.string.ui_channel_auto,
    "Security" to R.string.ui_security,
    "Open" to R.string.ui_open_network,
    "WPA3 transition" to R.string.ui_wpa3_transition,
    "Board I2C diagnostic" to R.string.ui_main_diag_title,
    "Linux I2C device" to R.string.ui_linux_i2c_device,
    "Run MFi self-check" to R.string.ui_run_mfi_check,
    "CH341 requires deployment-specific VID/PID configuration." to R.string.ui_ch341_vid_pid,
    "Idle" to R.string.ui_idle,
    "Running…" to R.string.ui_running,
    "MFi scan interrupted" to R.string.ui_mfi_scan_interrupted,
    "Found: none" to R.string.ui_found_none,
    "Getting CarPlay ready…" to R.string.ui_host_ready,
    "Reset CarPlay Wi-Fi" to R.string.ui_reset_carplay_wifi,
    "Back to DiPlay" to R.string.ui_back_to_diplay,
    "In CarPlay, swipe down with three fingers to open DiPlay settings." to R.string.ui_host_settings_gesture,
    "Keep your iPhone nearby with Bluetooth and Wi-Fi on.\nAllow CarPlay if your iPhone asks." to R.string.ui_host_wireless_instructions,
    "Use a USB data cable and unlock your iPhone.\nAllow Trust and CarPlay if your iPhone asks." to R.string.ui_host_usb_instructions,
    "Wireless CarPlay transport" to R.string.ui_wireless_carplay_setting,
    "Wireless hotspot: off" to R.string.ui_hotspot_status_off,
    "CarPlay icon" to R.string.ui_carplay_icon,
    "Hotspot SSID" to R.string.ui_hotspot_ssid_label,
    "Car hotspot name" to R.string.ui_car_hotspot_name,
    "Car hotspot password" to R.string.ui_car_hotspot_password,
    "Large" to R.string.ui_carplay_size_large,
    "Medium" to R.string.ui_carplay_size_medium,
    "Small" to R.string.ui_carplay_size_small,
    "Start CarPlay automatically after device boot" to R.string.ui_auto_start_carplay,
    "Remote" to R.string.ui_remote,
    "The following settings are unavailable and hidden on Android 9 (API 28):\n• Wi-Fi P2P (5 GHz) — LocalOnlyHotspot is used instead.\n• HEVC software decoder — hardware decoding is used instead." to R.string.ui_android9_settings_unavailable,
    "I2C device path is required" to R.string.ui_mfi_i2c_required,
    "Remote server address is required" to R.string.ui_mfi_server_required,
    "Remote server address must start with http:// or https://" to R.string.ui_mfi_server_scheme,
    "I2C device path contains U+0000" to R.string.ui_mfi_path_nul,
    "Remote server address contains U+0000" to R.string.ui_mfi_server_nul,
    "Remote token contains U+0000" to R.string.ui_mfi_token_nul,
    "Hotspot SSID is required" to R.string.ui_hotspot_ssid_required,
    "Hotspot SSID must be at most 32 UTF-8 bytes" to R.string.ui_hotspot_ssid_too_long,
    "Hotspot SSID contains U+0000" to R.string.ui_hotspot_ssid_nul,
    "Channel must be 0 or 1-196" to R.string.ui_hotspot_channel_invalid,
    "Channel is not valid for the selected band" to R.string.ui_hotspot_channel_band,
    "Hotspot password contains U+0000" to R.string.ui_hotspot_password_nul,
    "Password must be empty when security is Open" to R.string.ui_hotspot_open_password,
    "WPA2/WPA3 password must be 8-63 characters" to R.string.ui_hotspot_password_length,
    "Enter the car hotspot name" to R.string.ui_hotspot_enter_name,
    "The hotspot name must be at most 32 bytes" to R.string.ui_hotspot_name_bytes,
    "The name or password contains an invalid character" to R.string.ui_hotspot_invalid_char,
    "The hotspot password must be 8–63 characters" to R.string.ui_hotspot_password_chars,
    "Starting" to R.string.ui_hotspot_starting,
    "Ready" to R.string.ui_hotspot_ready,
    "off" to R.string.ui_hotspot_off,
    "stopped" to R.string.ui_hotspot_stopped,
    "Running" to R.string.ui_hotspot_running,
    "Active" to R.string.ui_hotspot_active,
    "Error" to R.string.ui_hotspot_error,
    "Starting AirPlay service" to R.string.ui_hotspot_starting_airplay,
    "Waiting for paired iPhone" to R.string.ui_hotspot_waiting_iphone,
    "Connecting Bluetooth" to R.string.ui_hotspot_connecting_bluetooth,
    "top hidden" to R.string.ui_top_hidden,
    "top shown" to R.string.ui_top_shown,
    "bottom hidden" to R.string.ui_bottom_hidden,
    "bottom shown" to R.string.ui_bottom_shown,
    "right" to R.string.ui_right,
    "left" to R.string.ui_left,
    "enabled" to R.string.ui_enabled,
    "disabled" to R.string.ui_disabled,
    "AAOS buses" to R.string.ui_aaos_buses,
    "Mobile compatible" to R.string.ui_mobile_compatible,
    "software" to R.string.ui_software,
    "hardware" to R.string.ui_hardware,
    "The following settings are unavailable and hidden on Android 9 (API 28):\n" +
        "• Wi-Fi P2P (5 GHz) — LocalOnlyHotspot is used instead.\n" +
        "• HEVC software decoder — hardware decoding is used instead." to R.string.ui_android9_settings_unavailable,
)
